server:
  port: 18002

dubbo:
#  application:
#    qos-accept-foreign-ip: false
#    qos-port: 48002
#    qos-enable: true
  scan:
    #扫描Dubbo服务的路径
    base-packages: com.want.versions.provider.api
  provider:
    #服务端的统一版本
    version: 1.0.0
  cloud:
    #订阅的服务
    subscribed-services: ''
  protocols:
    dubbo:
      #dubbo 端口
      port: 38002
      serialization: kryo
      optimizer: com.want.version.demo.optimizer.SerializationOptimizerImpl


