server:
  port: 18000

dubbo:
  scan:
    #扫描Dubbo服务的路径
    base-packages: com.want.demo.provider.api
  provider:
    #服务端的统一版本
    version: 1.0.0
  cloud:
    #订阅的服务
    subscribed-services: ''
  protocols:
    http:
      #dubbo 端口
      server: tomcat
      port: 18001


